name: location_manager
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.8
  location: 4.4.0
  permission_handler: 9.2.0
  location_permissions: 4.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.6.0
